plugins {
    id 'com.android.application'
}

android {
    namespace 'com.device.manager'
    compileSdk 36
    buildToolsVersion '36.1.0'

    defaultConfig {
        applicationId 'com.device.manager'
        minSdk 24
        targetSdk 34
        versionCode 201
        versionName '2.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}
